# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "christt105's Blog"
weight = 1

[es]
languageName = "Español"
languagedirection = "ltr"
title = "christt105 Blog"
weight = 2

[ca]
languageName = "Català"
languagedirection = "ltr"
title = "christt105 Blog"
weight = 3
