# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/christt105"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/christianmartinezdelarosa/"

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "itch.io"
name = "Itch.io"
url = "https://christt105.itch.io/"

[social.params]
icon = "brand-itch"

[[social]]
identifier = "discord"
name = "Discord"
url = "https://discordapp.com/users/360439358395908099"

[social.params]
icon = "brand-discord"

[[social]]
identifier = "telegram"
name = "Telegram"
url = "https://t.me/christt105"

[social.params]
icon = "brand-telegram"
